version: '3.3'

services:
  db:
    image: postgres:14.3
    restart: always
    container_name: pizzaria-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pizzaria
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.8.1
    restart: always
    container_name: pizzaria-adminer
    ports:
      - 8909:8080
